[webserver]
port = ":8080"

[cache]
type="file"             # cache type
basepath="/tmp/tegola"  # cache specific config

# register data providers
[[providers]]
name = "db1"                # provider name is referenced from map layers
type = "postgis"            # the type of data provider. currently only supports postgis
host = "${POSTGIS_HOST}"    # postgis database host
port = "${POSTGIS_PORT}"    # postgis database port
database = "${POSTGIS_DB}"  # postgis database name
user = "${POSTGIS_USER}"    # postgis database user
password = "${POSTGIS_PW}"  # postgis database password
srid = 3857                 # The default srid for this provider. If not provided it will be WebMercator (3857)
ssl_mode = "allow"

  [[providers.layers]]
  name = "bevarede_lokalplaner"
  tablename = "bevarende_lokalplaner"

  [[providers.layers]]
  name = "kommuneplanrammer"
  tablename = "kommuneplanrammer"

  [[providers.layers]]
  name = "kommuneplantillaeg"
  tablename = "kommuneplantillaeg"

  [[providers.layers]]
  name = "lokalplan"
  tablename = "lokalplan"

  [[providers.layers]]
  name = "lokalplaner_forslag"
  tablename = "lokalplaner_forslag"

  [[providers.layers]]
  name = "fredet_bevaringsvaerdig_bygning"
  tablename = "fredet_bevaringsvaerdig_bygning"

  [[providers.layers]]
  name = "temalokalplaner"
  tablename = "temalokalplaner"

  [[providers.layers]]
  name = "jordforurening"
  tablename = "jordforurening"

  [[providers.layers]]
  name = "matrikel"
  tablename = "matrikel"

  [[providers.layers]]
  name = "nedsivning_potentiale"
  tablename = "nedsivning_potentiale"

[[maps]]
name = "Byggeri og planlægning"
center = [12.52358, 55.68115, 13.0]

  [[maps.layers]]
  name = "Bevarede lokalplaner"
  provider_layer = "db1.bevarede_lokalplaner"
  min_zoom = 10
  max_zoom = 20

  [[maps.layers]]
  provider_layer = "db1.kommuneplanrammer"
  min_zoom = 10
  max_zoom = 20

  [[maps.layers]]
  provider_layer = "db1.kommuneplantillaeg"
  min_zoom = 10
  max_zoom = 20

  [[maps.layers]]
  provider_layer = "db1.lokalplan"
  min_zoom = 10
  max_zoom = 20

  [[maps.layers]]
  provider_layer = "db1.lokalplaner_forslag"
  min_zoom = 10
  max_zoom = 20

  [[maps.layers]]
  provider_layer = "db1.temalokalplaner"
  min_zoom = 10
  max_zoom = 20

  [[maps.layers]]
  provider_layer = "db1.fredet_bevaringsvaerdig_bygning"
  min_zoom = 10
  max_zoom = 20

  [[maps.layers]]
  provider_layer = "db1.jordforurening"
  min_zoom = 10
  max_zoom = 20

  [[maps.layers]]
  provider_layer = "db1.matrikel"
  min_zoom = 10
  max_zoom = 20

  [[maps.layers]]
  provider_layer = "db1.nedsivning_potentiale"
  min_zoom = 10
  max_zoom = 20
