[webserver]
port = ":8080"

[cache]
type="file"             # cache type
basepath="/tmp/tegola"  # cache specific config

# register data providers
[[providers]]
name = "db1"                # provider name is referenced from map layers
type = "postgis"            # the type of data provider. currently only supports postgis
host = "${POSTGIS_HOST}"    # postgis database host
port = "${POSTGIS_PORT}"    # postgis database port
database = "${POSTGIS_DB}"  # postgis database name
user = "${POSTGIS_USER}"    # postgis database user
password = "${POSTGIS_PW}"  # postgis database password
srid = 3857                 # The default srid for this provider. If not provided it will be WebMercator (3857)
max_connections = 50        # There's configured 50 connections in the pool for this DB in DO
ssl_mode = "require"


  [[providers.layers]]
  name = "aabne_friarealer"
  tablename = "aabne_friarealer"

  [[providers.layers]]
  name = "fredet_bygning"
  tablename = "fredet_bevaringsvaerdig_bygning"

  [[providers.layers]]
  name = "vandposter"
  tablename = "vandposter"

  [[providers.layers]]
  name = "valgdistrikter"
  tablename = "valgdistrikter"

  [[providers.layers]]
  name = "traer"
  tablename = "traer"

  [[providers.layers]]
  name = "temalokalplaner"
  tablename = "temalokalplaner"

  [[providers.layers]]
  name = "sportsanlaeg"
  tablename = "sportsanlaeg"

  [[providers.layers]]
  name = "sociale_institutioner"
  tablename = "sociale_institutioner"

  [[providers.layers]]
  name = "skulptur"
  tablename = "skulptur"

  [[providers.layers]]
  name = "skoler"
  tablename = "skoler"

  [[providers.layers]]
  name = "skoledistrikter_6_9"
  tablename = "skoledistrikter_6_9"

  [[providers.layers]]
  name = "skoledistrikter_0_5"
  tablename = "skoledistrikter_0_5"

  [[providers.layers]]
  name = "sevaerdighed"
  tablename = "sevaerdighed"

  [[providers.layers]]
  name = "raadighedsareal"
  tablename = "raadighedsareal"

  [[providers.layers]]
  name = "punkter_motion"
  tablename = "punkter_motion"

  [[providers.layers]]
  name = "privatvej"
  tablename = "privatvej"

  [[providers.layers]]
  name = "plicens_salgssteder"
  tablename = "plicens_salgssteder"

  [[providers.layers]]
  name = "parkeringszone"
  tablename = "parkeringszone"

  [[providers.layers]]
  name = "p_automater"
  tablename = "p_automater"

  [[providers.layers]]
  name = "offentlige_toiletter"
  tablename = "offentlige_toiletter"

  [[providers.layers]]
  name = "offentlig_handicapparkering"
  tablename = "offentlig_handicapparkering"

  [[providers.layers]]
  name = "nedsivning_potentiale"
  tablename = "nedsivning_potentiale"

  [[providers.layers]]
  name = "multibaner"
  tablename = "multibaner"

  [[providers.layers]]
  name = "motionsruter"
  tablename = "motionsruter"

  [[providers.layers]]
  name = "matrikel"
  tablename = "matrikel"

  [[providers.layers]]
  name = "maling_indlevering"
  tablename = "maling_indlevering"

  [[providers.layers]]
  name = "lokalplaner_forslag"
  tablename = "lokalplaner_forslag"

  [[providers.layers]]
  name = "lokalplan"
  tablename = "lokalplan"

  [[providers.layers]]
  name = "legepladser"
  tablename = "legepladser"

  [[providers.layers]]
  name = "kultursteder"
  tablename = "kultursteder"

  [[providers.layers]]
  name = "kommuneplantillaeg"
  tablename = "kommuneplantillaeg"

  [[providers.layers]]
  name = "kommuneplanrammer"
  tablename = "kommuneplanrammer"

  [[providers.layers]]
  name = "kolonihaver"
  tablename = "kolonihaver"

  [[providers.layers]]
  name = "kirkegaarde"
  tablename = "kirkegaarde"

  [[providers.layers]]
  name = "jordforurening"
  tablename = "jordforurening"

  [[providers.layers]]
  name = "institutioner"
  tablename = "institutioner"

  [[providers.layers]]
  name = "idraetshaller"
  tablename = "idraetshaller"

  [[providers.layers]]
  name = "hunde_fritloebsomraader"
  tablename = "hunde_fritloebsomraader"

  [[providers.layers]]
  name = "gymnasier"
  tablename = "gymnasier"

  [[providers.layers]]
  name = "gronneomraader"
  tablename = "gronneomraader"

  [[providers.layers]]
  name = "glascontainere"
  tablename = "glascontainere"

  [[providers.layers]]
  name = "genbrugsstation"
  tablename = "genbrugsstation"

  [[providers.layers]]
  name = "genbrugs_oeer"
  tablename = "genbrugs_oeer"

  [[providers.layers]]
  name = "fritidsklubber"
  tablename = "fritidsklubber"

  [[providers.layers]]
  name = "elbilstandere"
  tablename = "elbilstandere"

  [[providers.layers]]
  name = "doegninstitutioner"
  tablename = "doegninstitutioner"

  [[providers.layers]]
  name = "delebilpladser"
  tablename = "delebilpladser"

  [[providers.layers]]
  name = "cykelstier"
  tablename = "cykelstier"

  [[providers.layers]]
  name = "cykelpumpestation"
  tablename = "cykelpumpestation"

  [[providers.layers]]
  name = "bycykel_station"
  tablename = "bycykel_station"

  [[providers.layers]]
  name = "bolig_aeldre_handicap"
  tablename = "bolig_aeldre_handicap"

  [[providers.layers]]
  name = "bibliotek"
  tablename = "bibliotek"

  [[providers.layers]]
  name = "bevarende_lokalplaner"
  tablename = "bevarende_lokalplaner"

  [[providers.layers]]
  name = "apotek_indlevering"
  tablename = "apotek_indlevering"


#__/\\\\____________/\\\\_____/\\\\\\\\\_____/\\\\\\\\\\\\\_______/\\\\\\\\\\\___        
# _\/\\\\\\________/\\\\\\___/\\\\\\\\\\\\\__\/\\\/////////\\\___/\\\/////////\\\_       
#  _\/\\\//\\\____/\\\//\\\__/\\\/////////\\\_\/\\\_______\/\\\__\//\\\______\///__      
#   _\/\\\\///\\\/\\\/_\/\\\_\/\\\_______\/\\\_\/\\\\\\\\\\\\\/____\////\\\_________     
#    _\/\\\__\///\\\/___\/\\\_\/\\\\\\\\\\\\\\\_\/\\\/////////_________\////\\\______    
#     _\/\\\____\///_____\/\\\_\/\\\/////////\\\_\/\\\_____________________\////\\\___   
#      _\/\\\_____________\/\\\_\/\\\_______\/\\\_\/\\\______________/\\\______\//\\\__  
#       _\/\\\_____________\/\\\_\/\\\_______\/\\\_\/\\\_____________\///\\\\\\\\\\\/___ 
#        _\///______________\///__\///________\///__\///________________\///////////_____

# ----------------
# BYG & PLANLÆGNING
# ----------------
[[maps]]
name = "Byggeri og planlægning"
center = [12.52358, 55.68115, 13.0]

  [[maps.layers]]
  name = "Bevarende lokalplaner"
  provider_layer = "db1.bevarende_lokalplaner"

  [[maps.layers]]
  name = "Kommuneplanrammer"
  provider_layer = "db1.kommuneplanrammer"

  [[maps.layers]]
  name = "Kommuneplantillæg"
  provider_layer = "db1.kommuneplantillaeg"

  [[maps.layers]]
  name = "Lokalplaner"
  provider_layer = "db1.lokalplan"

  [[maps.layers]]
  name = "Lokalplan forslag"
  provider_layer = "db1.lokalplaner_forslag"

  [[maps.layers]]
  name = "Temalokalokalplaner"
  provider_layer = "db1.temalokalplaner"

  [[maps.layers]]
  name = "Bevaringsværdige bygninger"
  provider_layer = "db1.fredet_bevaringsvaerdig_bygning"

  [[maps.layers]]
  name = "Jordforurening"
  provider_layer = "db1.jordforurening"

  [[maps.layers]]
  name = "Matrikler"
  provider_layer = "db1.matrikel"

  [[maps.layers]]
  name = "Nedsivningspotentiale"
  provider_layer = "db1.nedsivning_potentiale"

  [[maps.layers]]
  name = "Rådighedsareal"
  provider_layer = "db1.raadighedsareal"


#----------------
# BØRN OG UNGE
#----------------
[[maps]]
name = "Børn og unge"
center = [12.52358, 55.68115, 13.0]

  [[maps.layers]]
  name = "Børneinstitutioner"
  provider_layer = "db1.institutioner"

  [[maps.layers]]
  name = "Døgninstitutioner"
  provider_layer = "db1.doegninstitutioner"

  [[maps.layers]]
  name = "Skoler"
  provider_layer = "db1.skoler"

  [[maps.layers]]
  name = "Gymnasier"
  provider_layer = "db1.gymnasier"

  [[maps.layers]]
  name = "Fritidsklubber"
  provider_layer = "db1.fritidsklubber"

  [[maps.layers]]
  name = "Legepladser"
  provider_layer = "db1.legepladser"

  [[maps.layers]]
  name = "Åbne friarealer"
  provider_layer = "db1.aabne_friarealer"

  [[maps.layers]]
  name = "Multibaner"
  provider_layer = "db1.multibaner"

  [[maps.layers]]
  name = "Skoledistrikter 0.-5. klasse"
  provider_layer = "db1.skoledistrikter_0_5"

  [[maps.layers]]
  name = "Skoledistrikter 6.-9. klasse"
  provider_layer = "db1.skoledistrikter_6_9"


# -------------
# KULTUR
# -------------
[[maps]]
name = "Kultur"
center = [12.52358, 55.68115, 13.0]

  [[maps.layers]]
  name = "Biblioteker"
  provider_layer = "db1.bibliotek"

  [[maps.layers]]
  name = "Kultursteder"
  provider_layer = "db1.kultursteder"

  [[maps.layers]]
  name = "Seværdigheder"
  provider_layer = "db1.sevaerdighed"

  [[maps.layers]]
  name = "Skulpturer"
  provider_layer = "db1.skulptur"

  [[maps.layers]]
  name = "Kirkegårde"
  provider_layer = "db1.kirkegaarde"

  [[maps.layers]]
  name = "Offentlige toiletter"
  provider_layer = "db1.offentlige_toiletter"

  [[maps.layers]]
  name = "Valgdistrikter"
  provider_layer = "db1.valgdistrikter"


# -------------
# Grøn og aktiv
# -------------
[[maps]]
name = "Grøn og aktiv"
center = [12.52358, 55.68115, 13.0]

  [[maps.layers]]
  name = "Aktivitetsspots"
  provider_layer = "db1.punkter_motion"

  [[maps.layers]]
  name = "Motionsruter"
  provider_layer = "db1.motionsruter"

  [[maps.layers]]
  name = "Multibaner"
  provider_layer = "db1.multibaner"

  [[maps.layers]]
  name = "Idrætshaller"
  provider_layer = "db1.idraetshaller"

  [[maps.layers]]
  name = "Sportsanlæg"
  provider_layer = "db1.sportsanlaeg"

  [[maps.layers]]
  name = "Legepladser"
  provider_layer = "db1.legepladser"

  [[maps.layers]]
  name = "Åbne friarealer"
  provider_layer = "db1.aabne_friarealer"

  [[maps.layers]]
  name = "Kolonihaver"
  provider_layer = "db1.kolonihaver"

  [[maps.layers]]
  name = "Kirkegårde"
  provider_layer = "db1.kirkegaarde"

  [[maps.layers]]
  name = "Parker og haver"
  provider_layer = "db1.gronneomraader"

  [[maps.layers]]
  name = "Fritløbsområder til hunde"
  provider_layer = "db1.hunde_fritloebsomraader"

  [[maps.layers]]
  name = "Vandposter"
  provider_layer = "db1.vandposter"

  [[maps.layers]]
  name = "Offentlige toiletter"
  provider_layer = "db1.offentlige_toiletter"
  
# -------------
# Trafik og Parkering
# -------------
[[maps]]
name = "Trafik og Parkering"
center = [12.52358, 55.68115, 13.0]

  [[maps.layers]]
  name = "Parkeringszone"
  provider_layer = "db1.parkeringszone"

  [[maps.layers]]
  name = "P-automater"
  provider_layer = "db1.p_automater"

  [[maps.layers]]
  name = "P-licens-salgssteder"
  provider_layer = "db1.plicens_salgssteder"

  [[maps.layers]]
  name = "Offentlig handicapparkering"
  provider_layer = "db1.offentlig_handicapparkering" 

  [[maps.layers]]
  name = "Elbilstandere"
  provider_layer = "db1.elbilstandere"
  
  [[maps.layers]]
  name = "Delebilpladser"
  provider_layer = "db1.delebilpladser"

  [[maps.layers]]
  name = "Private veje"
  provider_layer = "db1.privatvej"

  [[maps.layers]]
  name = "Cykelstier"
  provider_layer = "db1.cykelstier"

  [[maps.layers]]
  name = "Cykelpumpestationer"
  provider_layer = "db1.cykelpumpestation"

  [[maps.layers]]
  name = "Bycykel-ladestationer"
  provider_layer = "db1.bycykel_station"

  [[maps.layers]]
  name = "Vandposter"
  provider_layer = "db1.vandposter"

  # Vintervedligehold
  # MANGLER

  [[maps.layers]]
  name = "Matrikel"
  provider_layer = "db1.matrikel"

 
# -------------
# Social og sundhed
# -------------
[[maps]]
name = "Social og sundhed"
center = [12.52358, 55.68115, 13.0]

  [[maps.layers]]
  name = "Boliger til ældre og handicappede"
  provider_layer = "db1.bolig_aeldre_handicap"

  [[maps.layers]]
  name = "Sociale institutioner"
  provider_layer = "db1.sociale_institutioner"

  [[maps.layers]]
  name = "Offentlig handicapparkering"
  provider_layer = "db1.offentlig_handicapparkering"

# -------------
# Affald og genbrug
# -------------
[[maps]]
name = "Affald og genbrug"
center = [12.52358, 55.68115, 13.0]

  [[maps.layers]]
  name = "Genbrugsstation"
  provider_layer = "db1.genbrugsstation"

  [[maps.layers]]
  name = "Glas"
  provider_layer = "db1.glascontainere"

  [[maps.layers]]
  name = "Genbrugs-øer"
  provider_layer = "db1.genbrugs_oeer"

  [[maps.layers]]
  name = "Apoteker"
  provider_layer = "db1.apotek_indlevering"
  
  [[maps.layers]]
  name = "Malerbutikker"
  provider_layer = "db1.maling_indlevering"
