[webserver]
port = ":8080"

[cache]
type="file"             # cache type
basepath="/tmp/tegola"  # cache specific config

# register data providers
[[providers]]
name = "db1"                # provider name is referenced from map layers
type = "postgis"            # the type of data provider. currently only supports postgis
host = "${POSTGIS_HOST}"    # postgis database host
port = "${POSTGIS_PORT}"    # postgis database port
database = "${POSTGIS_DB}"  # postgis database name
user = "${POSTGIS_USER}"    # postgis database user
password = "${POSTGIS_PW}"  # postgis database password
srid = 3857                 # The default srid for this provider. If not provided it will be WebMercator (3857)
max_connections = 50        # There's configured 50 connections in the pool for this DB in DO
ssl_mode = "require"

  [[providers.layers]]
  name = "matrikel"
  tablename = "matrikel"

  [[providers.layers]]
  name = "jordforurening"
  tablename = "jordforurening"

  [[providers.layers]]
  name = "nedsivning_potentiale"
  tablename = "nedsivning_potentiale"

  [[providers.layers]]
  name = "fredet_bevaringsvaerdig_bygning"
  tablename = "fredet_bevaringsvaerdig_bygning"

  [[providers.layers]]
  name = "lokalplan"
  tablename = "lokalplan"

  [[providers.layers]]
  name = "bevarende_lokalplaner"
  tablename = "bevarende_lokalplaner"

  [[providers.layers]]
  name = "temalokalplaner"
  tablename = "temalokalplaner"

  [[providers.layers]]
  name = "lokalplaner_forslag"
  tablename = "lokalplaner_forslag"

  [[providers.layers]]
  name = "kommuneplanrammer"
  tablename = "kommuneplanrammer"

  [[providers.layers]]
  name = "kommuneplantillaeg"
  tablename = "kommuneplantillaeg"

  [[providers.layers]]
  name = "raadighedsareal"
  tablename = "raadighedsareal"

  [[providers.layers]]
  name = "skoledistrikter_0_5"
  tablename = "skoledistrikter_0_5"

  [[providers.layers]]
  name = "institutioner"
  tablename = "institutioner"

  [[providers.layers]]
  name = "doegninstitutioner"
  tablename = "doegninstitutioner"

  [[providers.layers]]
  name = "skoler"
  tablename = "skoler"

  [[providers.layers]]
  name = "gymnasier"
  tablename = "gymnasier"

  [[providers.layers]]
  name = "fritidsklubber"
  tablename = "fritidsklubber"

  [[providers.layers]]
  name = "legepladser"
  tablename = "legepladser"

  [[providers.layers]]
  name = "skoledistrikter_6_9"
  tablename = "skoledistrikter_6_9"

  [[providers.layers]]
  name = "aabne_friarealer"
  tablename = "aabne_friarealer"

  [[providers.layers]]
  name = "multibaner"
  tablename = "multibaner"

[[maps]]
name = "Byggeri og planlægning"
center = [12.52358, 55.68115, 13.0]

  [[maps.layers]]
  name = "Bevarende lokalplaner"
  provider_layer = "db1.bevarende_lokalplaner"
  min_zoom = 10
  max_zoom = 20

  [[maps.layers]]
  name = "Kommuneplanrammer"
  provider_layer = "db1.kommuneplanrammer"
  min_zoom = 10
  max_zoom = 20

  [[maps.layers]]
  name = "Kommuneplantillæg"
  provider_layer = "db1.kommuneplantillaeg"
  min_zoom = 10
  max_zoom = 20

  [[maps.layers]]
  name = "Lokalplaner"
  provider_layer = "db1.lokalplan"
  min_zoom = 10
  max_zoom = 20

  [[maps.layers]]
  name = "Lokalplan forslag"
  provider_layer = "db1.lokalplaner_forslag"
  min_zoom = 10
  max_zoom = 20

  [[maps.layers]]
  name = "Temalokalokalplaner"
  provider_layer = "db1.temalokalplaner"
  min_zoom = 10
  max_zoom = 20

  [[maps.layers]]
  name = "Fredede og bevaringsværdige bygninger"
  provider_layer = "db1.fredet_bevaringsvaerdig_bygning"
  min_zoom = 10
  max_zoom = 20

  [[maps.layers]]
  name = "Jordforurening"
  provider_layer = "db1.jordforurening"
  min_zoom = 10
  max_zoom = 20

  [[maps.layers]]
  name = "Matrikler"
  provider_layer = "db1.matrikel"
  min_zoom = 10
  max_zoom = 20

  [[maps.layers]]
  name = "Nedsivningspotentiale"
  provider_layer = "db1.nedsivning_potentiale"
  min_zoom = 10
  max_zoom = 20
  
  [[maps.layers]]
  name = "Rådighedsareal"
  provider_layer = "db1.raadighedsareal"
  min_zoom = 10
  max_zoom = 20

[[maps]]
name = "Børn og unge"
center = [12.52358, 55.68115, 13.0]

  [[maps.layers]]
  name = "Børneinstitutioner"
  provider_layer = "db1.institutioner"
  min_zoom = 10
  max_zoom = 20

  [[maps.layers]]
  name = "Døgninstitutioner"
  provider_layer = "db1.doegninstitutioner"
  min_zoom = 10
  max_zoom = 20

  [[maps.layers]]
  name = "Skoler"
  provider_layer = "db1.skoler"
  min_zoom = 10
  max_zoom = 20

  [[maps.layers]]
  name = "Gymnasier"
  provider_layer = "db1.gymnasier"
  min_zoom = 10
  max_zoom = 20

  [[maps.layers]]
  name = "Fritidsklubber"
  provider_layer = "db1.fritidsklubber"
  min_zoom = 10
  max_zoom = 20

  [[maps.layers]]
  name = "Legepladser"
  provider_layer = "db1.legepladser"
  min_zoom = 10
  max_zoom = 20

  [[maps.layers]]
  name = "Åbne friarealer"
  provider_layer = "db1.aabne_friarealer"
  min_zoom = 10
  max_zoom = 20

  [[maps.layers]]
  name = "Multibaner"
  provider_layer = "db1.multibaner"
  min_zoom = 10
  max_zoom = 20
  
  [[maps.layers]]
  name = "Skoledistrikter 0.-5. klasse (2016/17)"
  provider_layer = "db1.skoledistrikter_0_5"
  min_zoom = 10
  max_zoom = 20

  [[maps.layers]]
  name = "Skoledistrikter 6.-9. klasse (2016/17)"
  provider_layer = "db1.skoledistrikter_6_9"
  min_zoom = 10
  max_zoom = 20
